---
# not use ufw in ZCU cloud
# add -A LOCAL iptables rules instead

- name: Insert iptables rule for SSH 22 single IP
  iptables:
    chain: INPUT
    protocol: tcp
    source: 46.23.61.151
    destination_port: 22
    jump: ACCEPT
    comment: "Allow SSH from JS home"


#- ufw:
#    rule: allow
#    port: '{{ssh_port}}'
#    proto: tcp
#  tags: ufw
#
#- ufw:
#    state: enabled
#  tags: ufw
#    
- name: SSH config
  blockinfile:
    dest: /etc/ssh/sshd_config
    block: |
      PermitRootLogin without-password
      Port {{ssh_port}}
  notify: restart sshd