# install Minecraft server via Ansible
# install just one server: ansible-playbook -l aether1 stack.yml
# ansible-galaxy install geerlingguy.docker
# ansible-galaxy collection install community.docker

---
- name: Install Basics
  hosts: all
  roles:
    - geerlingguy.docker      
    - basics
    - remote-access
    
- name: Minecraft server with plain docker
  hosts: ourea102,sulis23,sulis68,sulis20
  roles:
    - minecraft-user

- name: Minecraft server with docker compose
  hosts: sulis68
  roles:
    - minecraft-docker-compose
