# CIV cloud specific / add line to /etc/iptables/rules.v4.local
- name: Allow ssh from whole Internet via CIV cloud specific rules
  lineinfile:
    path: /etc/iptables/rules.v4.local
    line: -A INPUT -p tcp -m tcp --dport 22 -m comment --comment "22/SSH allowed from whole Internet" -j ACCEPT
    insertbefore: '^COMMIT'
    create: yes

# this should by done by cfengine based on rules.v4.local
- name: Firewall rule - allow port 22/SSH for the whole Internet
  iptables:
    chain: INPUT
    destination_port: 22
    jump: ACCEPT
    protocol: tcp
    comment: "22/SSH allowed from whole Internet"
