# CIV cloud specific - CF engine rules are OK here
# access via password auth allowed by default in sshd_config

# CIV cloud specific - remove cfengine - be aware!
# need to stop cfengine3
# systemctl disable cfengine
# systemctl disable cf-execd
# systemctl stop cfengine3
# comment /etc/cron.d/cfengine, stop the service cfengine3
# service cfengine3 status
# apt remove --purge cfengine-community
#- name: Disable cfengine by removing it
#  action: apt pkg=cfengine-community state=absent


# CIV cloud specific - /etc/hosts.allow
# /etc/hosts.allow
# comment sshd and add
# sshd: ALL
- name: Allow ssh from whole Internet in hosts.allow
  lineinfile:
    path: /etc/hosts.allow
    state: present
    regexp: '^sshd:'
    line: 'sshd: ALL'

# allow access to ssh for whole Internet
- include: iptables.yml


###########################################################
# see also https://github.com/joelhans/ssdnodes-ansible-provision
