# Minecraft server in container
#
# start minecraft server: docker-compose up -d 
# stop and remove docker container: docker-compose down

version: '3'

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - "/home/minecraft/mc/server-data:/data"
    environment:
      EULA: "TRUE"
      #VERSION: 1.16.3
      #TYPE: "BUKKIT"
      ENABLE_COMMAND_BLOCK: "TRUE"
      MOTD: "IoT lab ZCU Minecraft server"
      MEMORY: "4G"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "xxxxxx"

    #restart: always
