- name: Install pip
  apt: name=python-pip state=present

- name: install docker-py package
  pip: name=docker-py

- name: Ensure docker instance with minecraft server is running
  docker_container:
    name: mc
    image: itzg/minecraft-server
    volumes:
      - /home/minecraft/server-data:/data
    ports:
      - 25566:25565
    tty: yes
    interactive: yes
    env:
        EULA: "TRUE"
        ENABLE_COMMAND_BLOCK: "TRUE"
#	VERSION: "1.8.9"
        MOTD: "IoTlab ZCU Minecraft server"
        MEMORY: "3G"