- name: Install pip
  apt: name=python-pip state=present

- name: install docker-py package
  pip: name=docker-py

- name: Directory server-data/plugins
  file:
    path: /home/minecraft/server-data/plugins
    state: directory
    mode: 0775
    owner: minecraft
    group: minecraft

# absolute URL to one version of worldedit
# https://github.com/EngineHub/WorldEdit
- name: Install worldedit
  get_url:
    url: http://home.zcu.cz/~sitera/worldedit-bukkit-7.1.0-beta-1.jar
    dest: /home/minecraft/server-data/plugins
    mode: '0664'
    owner: minecraft
    group: minecraft

- name: Ensure docker instance with minecraft server is running
  docker_container:
    name: mc
    image: itzg/minecraft-server
    volumes:
      - /home/minecraft/server-data:/data
    ports:
      - 25566:25565
    tty: yes
    interactive: yes
    env:
        EULA: "TRUE"
        TYPE: "BUKKIT"
        ENABLE_COMMAND_BLOCK: "TRUE"
        VERSION: "1.15.1-R0.1-SNAPSHOT"
        MOTD: "IoTlab ZCU Minecraft server"
        MEMORY: "3G"