- name: Install pip
  apt: name=python-pip state=present

- name: install docker-py package
  pip: name=docker-py

# Plugins - installs plugins/mods from given URL
# - WorldEdit - https://github.com/EngineHub/WorldEdit
#   - note: WorldEdit needs OP player status
# World - installs world from zip file if none exists

- name: Ensure docker instance with minecraft server is running
  docker_container:
    name: mc
    image: itzg/minecraft-server
    volumes:
      - /home/minecraft/server-data:/data
    ports:
      - 25566:25565
    tty: yes
    interactive: yes
    env:
        EULA: "TRUE"
        # TYPE: "BUKKIT"
        TYPE: "PAPER"
        ENABLE_COMMAND_BLOCK: "TRUE"
        VERSION: "1.15.2"
        MOTD: "IoTlab ZCU Minecraft server"
        MEMORY: "3G"
        # WorldEdit URL / TODO find a better solution
        MODS: "http://home.zcu.cz/~sitera/worldedit-bukkit-7.1.0-beta-1.jar"
        # install this world if there is none
        WORLD: "http://home.zcu.cz/~sitera/MinecraftUltimateTutorial.zip"