- name: Ensure group minecraft exists
  group:
    name: minecraft
#    gid: 1000
    state: present

- name: Add the user minecraft
  user:
    name: minecraft
    uid: 1000
    comment: Minecraft Server
    group: minecraft
    groups: docker
    shell: /bin/bash

# allow ssh access via ssh key
- name: Setup authorized key
  authorized_key:
    user: minecraft
    state: present
    key: "{{ lookup('file', 'jirik.pub') }}"

