- name: Ensure group minecraft exists
  group:
    name: minecraft
    state: present

- name: Add the user minecraft
  user:
    name: minecraft
    comment: Minecraft Server
    group: minecraft
    groups: docker
    shell: /bin/bash

# create a directory if it doesn't exist
- name: Directory server-data
  file:
    path: /home/minecraft/server-data
    state: directory
    mode: 0775
    owner: minecraft
    group: minecraft

# CIV cloud specific / kerberos PAM module
# allow local password for users under 2000
- name: The kerberos module line 
  lineinfile:
    path: /etc/pam.d/common-password
    regexp: '^password.*pam_krb5.so'
    line: 'password        [success=2 default=ignore]      pam_krb5.so minimum_uid=2000'