- name: Ensure group minecraft exists
  group:
    name: minecraft
#    gid: 1000
    state: present

- name: Add the user minecraft
  user:
    name: minecraft
    uid: 1000
    comment: Minecraft Server
    group: minecraft
    groups: docker
    shell: /bin/bash

# create a directory if it doesn't exist
- name: Directory server-data
  file:
    path: /home/minecraft/server-data
    state: directory
    mode: 0775
    owner: minecraft
    group: minecraft

# allow ssh access via ssh key
- name: Setup authorized key
  authorized_key:
    user: minecraft
    state: present
    key: "{{ lookup('file', 'jirik.pub') }}"

