- name: Ensure group minecraft exists
  group:
    name: minecraft
    state: present

- name: Add the user minecraft
  user:
    name: minecraft
    comment: Minecraft Server
    group: minecraft
    groups: docker
    shell: /bin/bash

# create a directory if it doesn't exist
- name: Directory server-data
  file:
    path: /home/minecraft/server-data
    state: directory
    mode: 0775
    owner: minecraft
    group: minecraft